# Generated by Django 5.1.5 on 2026-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='college_workplace',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='profile',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='private/government_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'No preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('keto', 'Keto'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-free')], default='none', max_length=30),
        ),
    ]
