# Generated by Django 5.1.5 on 2026-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_conversation_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='allergens',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='packaging',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_instructions',
            field=models.TextField(blank=True),
        ),
    ]
