# Generated by Django 5.1.5 on 2026-08-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_foodlisting_allergens_foodlisting_packaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('food_group', 'Food Group')], db_index=True, default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='food_listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_conversation', to='community.foodlisting'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
